### ISSUE TITLE
research hindi keyboard to include with app

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#130]

**Comment by KIRINPUTRA** [comment]
AFAIK, state-backed Inscript is the most widespread, most reliably
easy-to-find Devanāgarī layout out there. The layout was optimized for
Hindi.

**Comment by jaagameister** [comment]
amar says adding the indic keyboard will be complicated. first step is getting the custom keyboard with indic options (buttons) and then go from there.
