### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#21]
find short folk tales / childrens stories 
and making chat problems for them

150 words ish ?..

add image / illustration

**Comment by rohitrd** [comment]
This problem should be in Kannada or in English??

**Comment by jaagameister** [comment]
To begin with we can just do simple english stories.
We want to move towards having multiple language versions
of everything.

**Comment by jaagameister** [comment]
lets add reading comprehension questions

**Comment by SwatiQP** [comment]
@rohitacc We are working on it tomorrow. Request you to be there in the meeting.
