### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#3]
addition

**Comment by mmbmatteo** [comment]
if question is 3.5 + 1.5 = ?

answer has to be 5.0 in order to be correct.

We should decide if we want 5 also to be valide

**Comment by SwatiQP** [comment]
@jaagameister

**Comment by jaagameister** [comment]
Lets make 5.0 as well as 5 work

**Comment by SwatiQP** [comment]
@mmbmatteo Status?

**Comment by mmbmatteo** [comment]
Done!
