### ISSUE TITLE
can't type "hint"

### ISSUE THREAD

**Issue by KIRINPUTRA** [jaagameister/learning#42]
When I try to type letters in the app, somehow the letters don't make it to the screen / input line. Not sure if this is a general Android problem or if it's just my phone.

**Comment by jaagameister** [comment]
you need to type "." by itself
then you can type 
hint
or 
mission

this is because by default its expecting numeric input
so we need to do something to shift to text.

im open to other ways of doing this, or possibly 
giving the user more useful help info / guidance
