### ISSUE TITLE
% Percent problems

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#5]

**Comment by SwatiQP** [comment]
@bharat-patodi What's the status?

**Comment by bharat-patodi** [comment]
The android studio emulator isn't functional. Looking into it. Otherwise
the percent problem seemed complete.

**Comment by KIRINPUTRA** [comment]
@Bharat,

The Emulator doesn't work for me either. Don't know but this article could
be relevant: http://techzog.com/development/android-studio-high-ram-usage/
