### ISSUE TITLE
play store content

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#60]
title
80 character description  (mainly contains key words)
longer description
banner 1024 x 500
screen shots

**Comment by SwatiQP** [comment]
Title - **Shrini**
Short Character description  (mainly contains key words) - 80 characters - Work in progress
longer description - 4000 characters - Work in progress
banner 1024 x 500 - Work in progress
screen shots - Work in progress

**Comment by jaagameister** [comment]
Longer Description: https://github.com/jaagameister/learning/wiki
Icon: https://github.com/jaagameister/learning/blob/master/app/src/main/res/drawable/srini.png

short description: amar
screen shots: amar
banner:  .... i dunno, maybe we leave it blank or do something simple with the CFI logo on codeforindia.org .... lets not block on it .
