### ISSUE TITLE
spanish

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#64]

**Comment by SwatiQP** [comment]
@KIRINPUTRA What is it about? Are we adding another language to the app?

**Comment by avtarsandhu** [comment]
Perdon Senorita   ?

Date: Tue, 16 Feb 2016 22:55:44 -0800

**Comment by SwatiQP** [comment]
@avtarsandhu Wanted to know what this issue mean?

**Comment by KIRINPUTRA** [comment]
​Yeah, Srini speaks Spanish already, at this point.​ Not sure when to close
this issue — once the app is finalized? Or once the Spanish strings.xml
catch up to the English one? (Which it already has.)

**Comment by SwatiQP** [comment]
@KIRINPUTRA I guess it stays opened till we have spanish version of the app.
