### ISSUE TITLE
kanada language keyboard

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#71]
research what best kanada keyboard input there is that we can install on the tablets.

**Comment by KIRINPUTRA** [comment]
INDIC KEYBOARD gets my vote. Specifically — for Kannada — the Inscript and ಲಿಪ್ಯಂತರಣ options. 

https://play.google.com/store/apps/details?id=org.smc.inputmethod.indic

Many other options get it done. GOOGLE INDIC KEYBOARD only has the "English-washed", auto-complete type of input. SWYPE only has the "hardcore Kannada" (a la Inscript) type of option. I bet most Kannadophone adults would feel most comfortable with Google Indic, while it's hard to imagine "laymen" in today's India being able to use Swype for Kannada fluently — although it'd be by far the fastest way to type Kannada in a decolonized world. Maybe — maybe — some of our kids will learn Inscript Kannada now and be ready for Swype Kannada down the line.
