### ISSUE TITLE
CLI version expects answer before giving prompt upon entering new skill

### ISSUE THREAD

**Issue by KIRINPUTRA** [jaagameister/learning#88]
happens once upon entering each new skill

**Comment by SwatiQP** [comment]
Can any coder take this issue up?

**Comment by SwatiQP** [comment]
@dhey2k @mmbmatteo @rohitacc @KIRINPUTRA @harish-aka-shivi @bharat-patodi @kkeelor

**Comment by mmbmatteo** [comment]
Unelegantly fixed. Don't think it should support localisation since it's developers and debug-only stuff.
