### ISSUE TITLE
Create 100 most common nouns and Illustrate them

### ISSUE THREAD

**Issue by SwatiQP** [jaagameister/learning#93]

**Comment by KIRINPUTRA** [comment]
​​Some things that should probably be baked into the spreadsheet in
eye-catching style as reminders:
- We should pick objects attached to nouns that use common letters with
  regular spellings. This may differ some from language to language.
- Swapna can exercise some "artist's choice", regardless.
- For Kannada, we'll use the spoken colloquial vernacular throughout, in
  direct contravention of the convention (if any) that only the high language
  should appear in writing. Cf.
  http://karnatique.blogspot.in/2008/03/concept-of-h-and-l-kannada-disease.html
